version: '3.8'

services:
  # Base de datos MySQL (solo para desarrollo)
  mysql:
    image: mysql:8.0
    container_name: moneydiary-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DB:-moneydiary_db}
      MYSQL_USER: ${MYSQL_USER:-moneydiary_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-moneydiary_password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - moneydiary-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/juargo/moneydiary-api:latest
    container_name: moneydiary-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_DB=${MYSQL_DB:-moneydiary_db}
      - MYSQL_USER=${MYSQL_USER:-moneydiary_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-moneydiary_password}
    volumes:
      - ./data:/app/data
    networks:
      - moneydiary-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Volúmenes persistentes
volumes:
  mysql_data:
    driver: local

# Redes
networks:
  moneydiary-network:
    driver: bridge
