version: '3.8'

services:
  # API Backend (Python)
  api:
    image: ghcr.io/juargo/moneydiary-api:latest
    container_name: moneydiary-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - ENV=production
    volumes:
      - ./data:/app/data
    networks:
      - moneydiary-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
  # Frontend (sin SSL, directamente en puerto 80)
  frontend:
    image: ghcr.io/juargo/moneydiary-frontend:latest
    container_name: moneydiary-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://api:8000}
    networks:
      - moneydiary-network
    depends_on:
      - api

# Redes
networks:
  moneydiary-network:
    driver: bridge
