"""bank

Revision ID: 2bf73624c130
Revises: f258b7a3ff84
Create Date: 2025-05-03 20:57:45.512926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf73624c130'
down_revision: Union[str, None] = 'f258b7a3ff84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_banks_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_app_banks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_banks_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_banks_name'))
        batch_op.drop_index(batch_op.f('ix_app_banks_id'))
        batch_op.drop_index(batch_op.f('ix_app_banks_code'))

    op.drop_table('banks', schema='app')
    # ### end Alembic commands ###
