/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/auth/capabilities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Discover whether web and/or mobile Google login are active
         * @description Public endpoint (requires x-api-key only, session-public — no prior session needed), always mounted regardless of whether GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET (web) or GOOGLE_CLIENT_ID_ANDROID (mobile) are configured (AC-10). Each client reads its own field (googleLoginEnabled or googleLoginMobileEnabled) before rendering its own Google-login affordance.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Current activation state of Google login. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["AuthCapabilitiesResponse"];
                    };
                };
                /** @description Missing or invalid x-api-key. */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/demo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Create or resume a demo session
         * @description Public endpoint (requires x-api-key only) that creates a demo account or resumes an existing valid session, then redirects. No JSON response body — the session is conveyed via the `md_session` cookie (Set-Cookie) and the redirect target.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Session established (new demo or resumed existing); redirects to the app root. */
                readonly 302: {
                    headers: {
                        /** @description Always "/" — the app root. */
                        readonly Location?: string;
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rejected: request is not a top-level navigation (anti-embed Fetch-Metadata guard). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate-limited: too many demo requests from this IP. */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/google": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Start Google sign-in
         * @description Public endpoint (requires x-api-key only, session-public) that starts the OIDC Authorization Code + PKCE round trip with Google (AUTH-11). Must be reached via a true top-level browser navigation — see AUTH-17. Sets the short-lived `md_oauth` cookie (state/nonce/PKCE) and redirects to Google. 404 when Google login is not active (AUTH-16) — see GET /api/auth/capabilities.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Redirects to Google's OAuth 2.0 authorization endpoint. */
                readonly 302: {
                    headers: {
                        /** @description Google's authorization URL. */
                        readonly Location?: string;
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rejected: request is not a top-level navigation (anti-embed Fetch-Metadata guard, shared with GET /api/auth/demo). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Google login is not active — GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET are not both configured (AUTH-16). */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate-limited: too many Google login attempts from this IP (budget shared with the callback, design §6.4). */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/google/callback": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Complete Google sign-in
         * @description Public endpoint (requires x-api-key only, session-public) — Google's redirect target after consent. Validates `state` against the `md_oauth` cookie and the `id_token` (signature/iss/aud/exp/nonce) before any identity resolution (AUTH-12), then resolves the identity to an existing user (find-only, AUTH-14) and issues a session equivalent to password login (AUTH-13). Every failure cause — bad state, bad token, no matching user, an unexpected infra fault — produces the identical 302 redirect (AUTH-15): this contract intentionally does not distinguish them. DUAL MODE (US-041, VINC041-02/03): when `md_oauth` carries a signed `link` marker (set by POST /api/perfil/google/vincular), this same endpoint completes an EXPLICIT LINK instead of a login — it binds a Google identity to the CALLER's own account, issues NO new session, and redirects to `/configuracion?google=vinculado` on success or `/configuracion?google=error` on a modelled failure. A `link` marker that fails its integrity check rejects the WHOLE callback to the generic `/login?error=google` — it never falls back to the login path.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Success: sets `md_session` and redirects to "/". Failure (any cause): redirects to "/login?error=google" with no session — see AUTH-15. */
                readonly 302: {
                    headers: {
                        /** @description "/" on success, "/login?error=google" on any failure. */
                        readonly Location?: string;
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rejected: request is not a top-level navigation (same Fetch-Metadata guard as initiate, design §3). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Google login is not active — GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET are not both configured (AUTH-16). */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate-limited: too many Google login attempts from this IP (budget shared with initiate, design §6.4). */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/google/token": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Authenticate with a native Google id_token (mobile)
         * @description Public endpoint (requires x-api-key only, session-public — no prior session needed) that verifies a device-obtained Google id_token (AUTH-19) and, on success, issues a session identical in shape to POST /api/auth/login (AUTH-20). Every failure cause — invalid/expired/wrong-audience token, unverified email, no matching account, a demo-user match, an email already linked to a different googleSub, or a JWKS/network failure — produces the identical 401 body used by POST /api/auth/login (AUTH-21, anti-enumeration). No Set-Cookie: mobile uses Bearer + SecureStore. 404 when GOOGLE_CLIENT_ID_ANDROID is not configured (AUTH-22) — independent of GET /api/auth/google's activation gate.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly idToken: string;
                    };
                };
            };
            readonly responses: {
                /** @description Authentication succeeded — identical shape to POST /api/auth/login. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["AuthLoginResponse"];
                    };
                };
                /** @description Verification or identity resolution failed (scrubbed — never echoes the id_token or email; identical body to POST /api/auth/login for every cause, AUTH-21). */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Google login mobile is not active — GOOGLE_CLIENT_ID_ANDROID is not configured (AUTH-22). */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate-limited: too many attempts from this IP (own budget, distinct from /auth/login and GET /api/auth/google, design §6.4). */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Authenticate with email and password
         * @description Public endpoint (requires x-api-key only, session-public — no prior session needed) that authenticates a user and returns a session token (AUTH-01). Sets the `md_session` cookie (Set-Cookie) in addition to the JSON body.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly email: string;
                        readonly password: string;
                    };
                };
            };
            readonly responses: {
                /** @description Authentication succeeded. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["AuthLoginResponse"];
                    };
                };
                /** @description Invalid credentials (scrubbed — never echoes email/password). */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Rate-limited: too many failed login attempts from this IP/email combination. */
                readonly 429: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * End the current session
         * @description Public endpoint (requires x-api-key only, session-public) that invalidates the current session token (if any) and clears the `md_session` cookie. Always succeeds — an already missing or invalid token does not produce an error.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Session ended (or was already absent). No response body. */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Current session identity
         * @description Authenticated endpoint returning the identity of the current session (AUTH-09, DEMO-AUTH-05). Requires x-api-key + a valid session.
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Identity of the authenticated session. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                /** @description No valid session (missing, expired, or invalid token). */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/buckets/{bucket}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Bucket drill-down
         * @description Authenticated endpoint returning the transaction detail for a single spend bucket (US-017). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Month period, format YYYY-MM (e.g. 2026-07). Absent defaults to the current month. Format is validated by the domain, not this schema. */
                    readonly periodo?: string;
                };
                readonly header?: never;
                readonly path: {
                    /** @description Bucket name (raw path param). Validated against the domain enum by the use case, not this schema. */
                    readonly bucket: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Bucket detail for the resolved period. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["DetalleBucketResponse"];
                    };
                };
                /** @description Invalid bucket (unrecognized value) or invalid periodo — both domain-level (BucketInvalidoError / PeriodoInvalidoError). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/categorias": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List the caller's category catalog
         * @description Authenticated endpoint returning the caller's own categories with their nested classification patterns and an all-history `transaccionesCount` per category — the caller-scoped impact preview for a destructive delete (US-038, CAT038-02; US-039, CAT039-01). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation). Available to demo sessions (read-only, CAT038-08).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description The caller's full catalog. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        /**
         * Create a category
         * @description Authenticated endpoint that creates a category owned by the caller (US-038, CAT038-01). Requires x-api-key + a valid session. Rejected for demo sessions (403 DEMO_SOLO_LECTURA).
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly bucket: string;
                        readonly nombre: string;
                    };
                };
            };
            readonly responses: {
                /** @description Category created. */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CategoriaResponse"];
                    };
                };
                /** @description Invalid nombre/bucket, or a malformed request body. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description The calling session is a demo session (read-only catalog). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description A category with that nombre already exists for this user (case-insensitive). */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/categorias/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Delete a category
         * @description Authenticated endpoint that deletes a category and cascades its patterns, atomically (US-038, CAT038-04 as modified by US-039). The delete always succeeds for a category owned by the caller, whether it is referenced by transactions or not. Every Transaccion that referenced the deleted category survives with categoriaId: null and its original bucketId unchanged — no money moves between buckets. Requires x-api-key + a valid session. Rejected for demo sessions.
         */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Category (and its patterns) deleted. No response body. */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The calling session is a demo session (read-only catalog). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description Anti-enumeration: the category does not exist or does not belong to the authenticated user. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        /**
         * Rename and/or re-bucket a category
         * @description Authenticated endpoint that partially updates a category (US-038, CAT038-03). At least one of `nombre`/`bucket` MUST be present. When `bucket` actually changes, every historical Transaccion pointing at the category is re-stamped atomically. Requires x-api-key + a valid session. Rejected for demo sessions.
         */
        readonly patch: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly bucket?: string;
                        readonly nombre?: string;
                    };
                };
            };
            readonly responses: {
                /** @description Category updated. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CategoriaResponse"];
                    };
                };
                /** @description Invalid nombre/bucket, an empty body, or a malformed request body. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description The calling session is a demo session (read-only catalog). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description Anti-enumeration: the category does not exist or does not belong to the authenticated user. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description A category with that nombre already exists for this user (case-insensitive). */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
            };
        };
        readonly trace?: never;
    };
    readonly "/api/ingestas": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List ingestas
         * @description Authenticated endpoint returning the per-user ingesta history (US-004/US-018). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Ingesta list for the authenticated user. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["IngestasListResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        /**
         * Upload a bank statement
         * @description Authenticated endpoint that detects the bank, validates structure, normalizes, persists, and categorizes a bank statement file (US-004/US-005/US-011). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Bank statement file (.xlsx or .pdf). Extension/bank-format validation is a domain rule (ExtensionNoPermitidaError / BancoNoReconocidoError), not this schema.
                         */
                        readonly file: string;
                    };
                };
            };
            readonly responses: {
                /** @description Upload processed and persisted. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["IngestaUploadResponse"];
                    };
                };
                /** @description Invalid file — missing file field, disallowed extension, unrecognized bank, invalid structure/normalization, or an oversized file (>10 MB). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Persistence failure (infrastructure fault, not the uploaded file). */
                readonly 500: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/ingestas/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Delete an ingesta
         * @description Authenticated endpoint that cascade-deletes an ingesta and its transactions (US-018, ING-01/ING-02). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Ingesta id (raw path param). Existence/ownership is checked by the use case, not this schema. */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Ingesta deleted. No response body. */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Anti-enumeration: the ingesta does not exist or does not belong to the authenticated user. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/ingestas/preview": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Preview a bank statement (dry run)
         * @description Authenticated endpoint that detects the bank, validates structure, and normalizes a sample of a would-be upload WITHOUT persisting anything (US-003). Requires x-api-key + a valid session; the result itself is not scoped by user (no tenant data is touched).
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description Bank statement file (.xlsx or .pdf). Extension/bank-format validation is a domain rule (ExtensionNoPermitidaError / BancoNoReconocidoError), not this schema.
                         */
                        readonly file: string;
                    };
                };
            };
            readonly responses: {
                /** @description Preview sample computed (not persisted). */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PreviewIngestaResponse"];
                    };
                };
                /** @description Invalid file — missing file field, disallowed extension, unrecognized bank, invalid structure/normalization, or an oversized file (>10 MB). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/movimientos": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Monthly transaction list
         * @description Authenticated endpoint returning the consolidated monthly transaction list (US-014). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Month period, format YYYY-MM (e.g. 2026-07). Absent defaults to the current month. Format is validated by the domain, not this schema. */
                    readonly periodo?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Monthly transaction list for the resolved period. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["MovimientosMesResponse"];
                    };
                };
                /** @description Invalid periodo — either a transport-shape mismatch or a malformed YYYY-MM value (domain-level, PeriodoMes VO). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/patrones": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Create a classification pattern
         * @description Authenticated endpoint that creates a classification pattern under one of the caller's own categories (US-038, CAT038-05/06). Requires x-api-key + a valid session. Rejected for demo sessions.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly categoriaId: string;
                        readonly matchType: string;
                        readonly patron: string;
                        readonly prioridad?: number;
                    };
                };
            };
            readonly responses: {
                /** @description Pattern created. */
                readonly 201: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PatronResponse"];
                    };
                };
                /** @description Invalid patron/matchType/prioridad, an invalid REGEX (write-time compile check), or a malformed request body. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description The calling session is a demo session (read-only catalog). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description Anti-enumeration: categoriaId does not exist or does not belong to the authenticated user. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description A pattern with that text already exists for this user (case-insensitive). */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/patrones/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        /**
         * Delete a classification pattern
         * @description Authenticated endpoint that deletes a pattern (US-038, CAT038-05/07). Requires x-api-key + a valid session. Rejected for demo sessions.
         */
        readonly delete: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Pattern deleted. No response body. */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The calling session is a demo session (read-only catalog). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description Anti-enumeration: the pattern does not exist or does not belong to the authenticated user. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
            };
        };
        readonly options?: never;
        readonly head?: never;
        /**
         * Update a classification pattern
         * @description Authenticated endpoint that partially updates a pattern (US-038, CAT038-05). `categoriaId` is NOT accepted — moving a pattern between categories is a non-goal. Requires x-api-key + a valid session. Rejected for demo sessions.
         */
        readonly patch: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly matchType?: string;
                        readonly patron?: string;
                        readonly prioridad?: number;
                    };
                };
            };
            readonly responses: {
                /** @description Pattern updated. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PatronResponse"];
                    };
                };
                /** @description Invalid patron/matchType/prioridad, an invalid REGEX, an empty body, or a malformed request body. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description The calling session is a demo session (read-only catalog). */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description Anti-enumeration: the pattern does not exist or does not belong to the authenticated user. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
                /** @description A pattern with that text already exists for this user (case-insensitive). */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["CatalogoErrorResponse"];
                    };
                };
            };
        };
        readonly trace?: never;
    };
    readonly "/api/perfil": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Update the current user profile (nombre and/or email)
         * @description Authenticated endpoint that updates the caller's own nombre and/or email (US-040, PERF040-01/02/03/04/07). `passwordActual` is REQUIRED whenever `email` is present. On an email change the ciphertext and blind index are rewritten together in one atomic update, so login keeps working with the NEW address and stops working with the old one. A wrong `passwordActual` and an email already claimed by another account return the SAME generic 403 PERFIL_RECHAZADO (anti-enumeration) — 403, never 401: 401 is reserved for an invalid session. Requires x-api-key + a valid session. Rejected for demo sessions (403 DEMO_SOLO_LECTURA).
         */
        readonly patch: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly email?: string;
                        readonly nombre?: string;
                        readonly passwordActual?: string;
                    };
                };
            };
            readonly responses: {
                /** @description Profile updated; the full updated identity is returned. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["AuthMeResponse"];
                    };
                };
                /** @description Malformed body, or an invalid nombre/email. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
                /** @description No valid session (missing, expired, or invalid token). */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Demo session, wrong current password, or the email is already in use. */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
            };
        };
        readonly trace?: never;
    };
    readonly "/api/perfil/google/desvincular": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Unlink the Google identity from the current account
         * @description Authenticated endpoint (US-041, VINC041-05) that re-verifies the current password and clears the CALLER's own googleSub. Idempotent: a second call after success still responds 204. Rejected for demo sessions (403 DEMO_SOLO_LECTURA), for a wrong current password (403 PERFIL_RECHAZADO), and when the account has no passwordHash (403 VINCULO_REQUIERE_PASSWORD — CA-03: an account may never be left without an access method). Mounted unconditionally, independent of whether Google login is currently active.
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly passwordActual: string;
                    };
                };
            };
            readonly responses: {
                /** @description The Google identity is no longer linked. */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Malformed body. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
                /** @description No valid session (missing, expired, or invalid token). */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Demo session, an incorrect current password, or the account has no passwordHash to fall back on. */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/perfil/google/vincular": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Start linking a Google identity to the current account
         * @description Authenticated endpoint (US-041, VINC041-01/02) that re-verifies the current password and starts the OIDC round trip that will bind a Google identity to the CALLER's own account — no email matching is involved. Responds with the authorization URL and sets the short-lived `md_oauth` cookie carrying an HMAC-signed link intent; the client performs a top-level navigation to that URL. Completion happens at GET /api/auth/google/callback, which redirects to `/configuracion?google=vinculado` or `/configuracion?google=error` and issues NO new session. Rejected for demo sessions (403 DEMO_SOLO_LECTURA), for a wrong current password (403 PERFIL_RECHAZADO), and when the account already carries a Google identity (409 GOOGLE_YA_VINCULADO — unlink first). 404 when Google login is not active (AUTH-16).
         */
        readonly post: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly passwordActual: string;
                    };
                };
            };
            readonly responses: {
                /** @description The Google OAuth authorization URL to navigate to. Sets Set-Cookie: md_oauth (state, nonce, codeVerifier, signed link). */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["VincularGoogleResponse"];
                    };
                };
                /** @description Malformed body. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
                /** @description No valid session (missing, expired, or invalid token). */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Demo session, or an incorrect current password. */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
                /** @description Google login is not active — GOOGLE_CLIENT_ID/GOOGLE_CLIENT_SECRET are not both configured (AUTH-16). */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The account already has a linked Google identity. */
                readonly 409: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
                /** @description Google authorization is temporarily unreachable. */
                readonly 503: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
            };
        };
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/perfil/password": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Change the current user's password
         * @description Authenticated endpoint that changes the caller's own password (US-040, PERF040-03/05/06). `passwordActual` is REQUIRED. On success, EVERY OTHER active session belonging to the caller's user is revoked — the session that made this request stays valid. A wrong `passwordActual` returns the SAME generic 403 PERFIL_RECHAZADO used by `PATCH /api/perfil` (anti-enumeration) — 403, never 401: 401 is reserved for an invalid session. `passwordNueva` must satisfy the domain password rules (8-128 characters) — an invalid one is rejected with 400 PASSWORD_INVALIDA before any write. Requires x-api-key + a valid session. Rejected for demo sessions (403 DEMO_SOLO_LECTURA).
         */
        readonly patch: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        readonly passwordActual: string;
                        readonly passwordNueva: string;
                    };
                };
            };
            readonly responses: {
                /** @description Password changed. No response body — every other session was revoked. */
                readonly 204: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Malformed body, or an invalid passwordNueva. */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
                /** @description No valid session (missing, expired, or invalid token). */
                readonly 401: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Demo session, or an incorrect current password. */
                readonly 403: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["PerfilErrorResponse"];
                    };
                };
            };
        };
        readonly trace?: never;
    };
    readonly "/api/resumen": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Monthly 50/30/20 breakdown
         * @description Authenticated endpoint returning the 50/30/20 budget breakdown for a month (US-015/016). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Month period, format YYYY-MM (e.g. 2026-07). Absent defaults to the current month. Format is validated by the domain, not this schema. */
                    readonly periodo?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Monthly resumen for the resolved period. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["ResumenMesResponse"];
                    };
                };
                /** @description Invalid periodo — either a transport-shape mismatch or a malformed YYYY-MM value (domain-level, PeriodoMes VO). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/resumen/anual": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Annual 50/30/20 breakdown
         * @description Authenticated endpoint returning the 50/30/20 budget breakdown for all 12 months of a year (US-030). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Year, e.g. 2026. Absent defaults to the current year. Range/format is validated by the domain, not this schema. */
                    readonly anio?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Annual resumen for the resolved year. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["ResumenAnualResponse"];
                    };
                };
                /** @description Invalid anio — either a transport-shape mismatch or a malformed/out-of-range value (domain-level). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/resumen/semaforo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Semáforo detail: zone-band edges, diagnosis, and CLP-to-Verde advice
         * @description Authenticated sibling detail endpoint to GET /api/resumen (US-049): exposes the semáforo classification's WHY and WHAT-TO-DO — per-bucket zone-band edges, a backend-generated Spanish diagnosis naming the driving bucket(s), and a CLP amount+direction that would return each Amarillo/Rojo bucket to Verde. Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation, ISO-01/ISO-02).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: {
                    /** @description Month period, format YYYY-MM (e.g. 2026-07). Absent defaults to the current month. Format is validated by the domain, not this schema. */
                    readonly periodo?: string;
                };
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Semáforo detail for the resolved period. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["SemaforoDetalleResponse"];
                    };
                };
                /** @description Invalid periodo — either a transport-shape mismatch or a malformed YYYY-MM value (domain-level, PeriodoMes VO). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/transacciones/{id}/categoria": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Reclassify a transaction
         * @description Authenticated endpoint that manually reassigns a transaction to a category (and its derived bucket) (US-013 S4). Requires x-api-key + a valid session (RNF-SEC-006, per-user isolation).
         */
        readonly patch: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path: {
                    /** @description Transaction id (raw path param). Existence/ownership is checked by the use case, not this schema. */
                    readonly id: string;
                };
                readonly cookie?: never;
            };
            readonly requestBody?: {
                readonly content: {
                    readonly "application/json": {
                        /** @description Category name (e.g. "Supermercado"), resolved against the caller's own catalog (ADR-036/ADR-037 — no closed enum) by the use case (CategoriaDesconocidaError if it does not resolve), not this schema. */
                        readonly categoria: string;
                    };
                };
            };
            readonly responses: {
                /** @description Transaction reclassified. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["TransaccionesCategoriaResponse"];
                    };
                };
                /** @description Invalid categoria — the given name does not resolve against the caller's own catalog (scrubbed, CategoriaDesconocidaError; ADR-037 — the closed enum gate is retired). */
                readonly 400: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Anti-enumeration: the transaction does not exist or does not belong to the authenticated user. */
                readonly 404: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        readonly trace?: never;
    };
    readonly "/version": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Deployed build info
         * @description Public, unauthenticated endpoint exposing the currently deployed build (ADR-030).
         */
        readonly get: {
            readonly parameters: {
                readonly query?: never;
                readonly header?: never;
                readonly path?: never;
                readonly cookie?: never;
            };
            readonly requestBody?: never;
            readonly responses: {
                /** @description Build info for the currently deployed API instance. */
                readonly 200: {
                    headers: {
                        readonly [name: string]: unknown;
                    };
                    content: {
                        readonly "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description GET /api/auth/capabilities — feature-activation discovery for auth-related, environment-gated affordances (AC-10). googleLoginEnabled gates the web Google-login affordance; googleLoginMobileEnabled gates the mobile one — independent env configurations. */
        readonly AuthCapabilitiesResponse: {
            /** @description true when GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET are both configured (container.googleAuth !== undefined), false otherwise (AUTH-16). */
            readonly googleLoginEnabled: boolean;
            /** @description true when GOOGLE_CLIENT_ID_ANDROID is configured (container.googleAuthMobile !== undefined), false otherwise (AUTH-22). Computed independently of googleLoginEnabled — either, both, or neither may be true. */
            readonly googleLoginMobileEnabled: boolean;
        };
        /** @description POST /api/auth/login — successful authentication (AUTH-01). */
        readonly AuthLoginResponse: {
            /** @description ISO-8601 UTC timestamp. */
            readonly expiresAt: string;
            readonly token: string;
            readonly userId: string;
        };
        /** @description GET /api/auth/me and PATCH /api/perfil — the authenticated user identity, including whether Google is linked (AUTH-09, US-040, VINC041-08). */
        readonly AuthMeResponse: {
            /** @description null only for esDemo=true (demo) accounts — a domain invariant, not enforced by this schema. */
            readonly email: string | null;
            readonly esDemo: boolean;
            /** @description VINC041-08. Whether the account has a linked Google identity, derived from googleSub !== null. The raw googleSub never crosses this boundary. */
            readonly googleVinculado: boolean;
            readonly nombre: string;
            readonly userId: string;
        };
        /** @description Error body for the 4 new catalog endpoints (US-038). Not retrofitted onto pre-existing operations. */
        readonly CatalogoErrorResponse: {
            readonly code: string;
            readonly message: string;
        };
        /** @description GET /api/categorias — the authenticated caller's full catalog (US-038, CAT038-02). */
        readonly CatalogoResponse: {
            readonly categorias: readonly components["schemas"]["CategoriaResponse"][];
        };
        /** @description A category with its nested classification patterns and the all-history count of the caller's own referencing transactions (US-038, US-039 CAT039-01). */
        readonly CategoriaResponse: {
            readonly bucket: string;
            readonly id: string;
            readonly nombre: string;
            readonly patrones: readonly {
                readonly categoriaId: string;
                readonly id: string;
                readonly matchType: string;
                readonly patron: string;
                readonly prioridad: number;
            }[];
            readonly transaccionesCount: number;
        };
        /** @description GET /api/buckets/:bucket — bucket drill-down (US-017). */
        readonly DetalleBucketResponse: {
            /** @description Validated bucket name (echo, not raw input). */
            readonly bucket: string;
            /** @description Resolved period, format YYYY-MM. */
            readonly periodo: string;
            readonly transacciones: readonly {
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly abono: string;
                readonly banco: string;
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly cargo: string;
                /** @description Folded category, or null for Ingreso/SinCategoria rows. */
                readonly categoria: {
                    readonly id: string;
                    readonly nombre: string;
                } | null;
                readonly descripcion: string;
                /** @description ISO-8601 UTC timestamp. */
                readonly fecha: string;
                readonly id: string;
                readonly numeroCuenta: string;
                readonly tipoCuenta: string;
            }[];
        };
        /** @description GET /api/ingestas — per-user ingesta list (US-004/US-018). */
        readonly IngestasListResponse: {
            readonly ingestas: readonly {
                /** @description null when an early FALLIDA ingesta never resolved a bank. */
                readonly banco: string | null;
                /** @enum {string} */
                readonly estado: "PROCESADA" | "FALLIDA";
                /** @description ISO-8601 UTC timestamp. */
                readonly fecha: string;
                readonly id: string;
                readonly motivoFallo: string | null;
                readonly nombreArchivo: string;
                /** @description Row count, not money — plain JSON number. */
                readonly totalTransacciones: number;
            }[];
        };
        /** @description POST /api/ingestas — successful upload result (US-004/US-005/US-011). */
        readonly IngestaUploadResponse: {
            readonly archivo: {
                readonly extension: string;
                readonly nombre: string;
                readonly tamanoBytes: number;
            };
            readonly banco: string;
            /** @description Count of rows skipped as duplicates. Never omitted (CA-04). */
            readonly duplicadosOmitidos: number;
            readonly ingestaId: string;
            readonly numeroCuenta: string;
            readonly tipoCuenta: string;
            /** @description Row count, not money — plain JSON number. */
            readonly totalTransacciones: number;
            readonly transacciones: readonly {
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly abono: string;
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly cargo: string;
                readonly descripcion: string;
                /** @description ISO-8601 UTC timestamp. */
                readonly fecha: string;
            }[];
        };
        /** @description GET /api/movimientos — monthly transaction list (US-014). */
        readonly MovimientosMesResponse: {
            /** @description Resolved period, format YYYY-MM. */
            readonly periodo: string;
            readonly totalTransacciones: number;
            readonly transacciones: readonly {
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly abono: string;
                readonly banco: string;
                /** @description Bucket name (Bucket domain enum value). */
                readonly bucket: string;
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly cargo: string;
                /** @description Folded category, or null for Ingreso/SinCategoria rows. */
                readonly categoria: {
                    readonly id: string;
                    readonly nombre: string;
                } | null;
                readonly descripcion: string;
                /** @description ISO-8601 UTC timestamp. */
                readonly fecha: string;
                readonly id: string;
                readonly numeroCuenta: string;
                readonly tipoCuenta: string;
            }[];
        };
        /** @description A classification pattern (US-038). */
        readonly PatronResponse: {
            readonly categoriaId: string;
            readonly id: string;
            readonly matchType: string;
            readonly patron: string;
            readonly prioridad: number;
        };
        /** @description Error body for the /api/perfil* endpoints (US-040). */
        readonly PerfilErrorResponse: {
            readonly code: string;
            readonly message: string;
        };
        /** @description POST /api/ingestas/preview — dry-run sample of a would-be upload (US-003). */
        readonly PreviewIngestaResponse: {
            readonly banco: string;
            readonly estructura: {
                /** @description Row count PRE-dedupe, not money — plain JSON number. */
                readonly totalFilasDatos: number;
            };
            readonly muestra: readonly {
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly abono: string;
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly cargo: string;
                readonly descripcion: string;
                /** @description ISO-8601 UTC timestamp. */
                readonly fecha: string;
            }[];
            readonly numeroCuenta: string;
            readonly tipoCuenta: string;
        };
        /** @description GET /api/resumen/anual — 50/30/20 annual breakdown (US-030). */
        readonly ResumenAnualResponse: {
            readonly anio: number;
            /** @description Always 12 entries, Enero→Diciembre. */
            readonly meses: readonly components["schemas"]["ResumenMesResponse"][];
        };
        /** @description GET /api/resumen — 50/30/20 monthly breakdown (US-015/016). */
        readonly ResumenMesResponse: {
            /** @description Always 4 entries: Necesidades, Deseos, Ahorro, SinCategoria. */
            readonly buckets: readonly {
                /** @description Bucket name (Bucket domain enum value). */
                readonly bucket: string;
                /** @description Traffic-light health state, lowercase wire enum (US-016), or null. */
                readonly estadoSemaforo: ("verde" | "amarillo" | "rojo") | null;
                /** @description Basis-point percentage (0-10000). null when sinIngreso=true. */
                readonly porcentajeBp: number | null;
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly total: string;
            }[];
            /** @description US-045: count of uncategorized cargo transactions (row count, not money). Always present. */
            readonly cantidadSinCategoria: number;
            /** @description Worst traffic-light state across measured buckets, or null. */
            readonly estadoGlobal: ("verde" | "amarillo" | "rojo") | null;
            /** @description Resolved period, format YYYY-MM. */
            readonly periodo: string;
            readonly sinIngreso: boolean;
            /** @description Hardcoded 50/30/20 reference targets. */
            readonly targets: {
                readonly Ahorro: number;
                readonly Deseos: number;
                readonly Necesidades: number;
            };
            /** @description BigInt-safe decimal string amount (never a JSON number). */
            readonly totalIngreso: string;
        };
        /** @description GET /api/resumen/semaforo — semáforo detail: zone-band edges, diagnosis, and CLP-to-Verde advice (US-049). */
        readonly SemaforoDetalleResponse: {
            /** @description Always exactly 3 entries: Necesidades, Deseos, Ahorro (D-03). */
            readonly buckets: readonly {
                /** @description Zone-band edges used to compute this estado, sourced from the single BANDAS_SEMAFORO table (SEM-02). */
                readonly bandas: {
                    readonly amarilloMax: number;
                    readonly amarilloMin: number | null;
                    readonly verdeMax: number;
                    readonly verdeMin: number | null;
                };
                /** @description Bucket name (Bucket domain enum value). */
                readonly bucket: string;
                /** @description CLP-to-Verde advice (SEM-03/SEM-04). null when estadoSemaforo is verde or null. */
                readonly consejo: {
                    /** @enum {string} */
                    readonly direccion: "reducir" | "aumentar";
                    /** @description Spanish sentence containing the literal `{monto}` placeholder exactly once (SEM-10). */
                    readonly mensaje: string;
                    /** @description BigInt-safe decimal string amount (never a JSON number). */
                    readonly monto: string;
                } | null;
                /** @description Traffic-light health state, lowercase wire enum, or null. */
                readonly estadoSemaforo: ("verde" | "amarillo" | "rojo") | null;
                /** @description Bucket's 50/30/20 target center, in basis points (SEM-02). */
                readonly metaBp: number;
                /** @description Basis-point percentage (0-10000). null when sinIngreso=true. */
                readonly porcentajeBp: number | null;
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly total: string;
            }[];
            /** @description Bucket names sharing estadoGlobal severity. [] when Verde or sinIngreso. */
            readonly bucketsCriticos: readonly string[];
            /** @description Backend-generated Spanish sentence naming the driving bucket(s) (SEM-01). Never contains {monto}. */
            readonly diagnostico: string;
            /** @description Worst traffic-light state across the 3 spend buckets, or null. */
            readonly estadoGlobal: ("verde" | "amarillo" | "rojo") | null;
            /** @description Resolved period, format YYYY-MM. */
            readonly periodo: string;
            /** @description Re-exposed from /api/resumen, never recomputed independently (SEM-05). */
            readonly sinCategoria: {
                readonly cantidad: number;
                /** @description BigInt-safe decimal string amount (never a JSON number). */
                readonly total: string;
            };
            readonly sinIngreso: boolean;
            /** @description BigInt-safe decimal string amount (never a JSON number). */
            readonly totalIngreso: string;
        };
        /** @description PATCH /api/transacciones/:id/categoria — manual reclassification result (US-013 S4). */
        readonly TransaccionesCategoriaResponse: {
            /** @description Derived bucket name (echo, not raw input). */
            readonly bucket: string;
            readonly categoria: {
                readonly id: string;
                readonly nombre: string;
            };
            readonly id: string;
        };
        /** @description Deployed build info for the API — GET /version. */
        readonly VersionResponse: {
            /** @description ISO-8601 timestamp of when this process booted. */
            readonly builtAt: string;
            /** @description Short commit SHA, or "local" outside Render. */
            readonly commit: string;
            /** @description Git branch/ref, or "local" outside Render. */
            readonly ref: string;
            /** @description Package version (release-please, ADR-030). */
            readonly version: string;
        };
        /** @description POST /api/perfil/google/vincular — the Google OAuth authorization URL to navigate to (VINC041-01). */
        readonly VincularGoogleResponse: {
            readonly urlAutorizacion: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
