services:
  db:
    container_name: moneydiary-dev-db

  api:
    container_name: moneydiary-dev-api
    build:
      dockerfile: docker/backend/Dockerfile.dev
    volumes:
      - ../../apps/api:/app/apps/api # Montaje para hot-reload
    environment:
      - DEBUG=true
    command: uvicorn apps.api.app.main:app --host 0.0.0.0 --reload

  # web:
  #   container_name: moneydiary-dev-web
  #   build:
  #     dockerfile: docker/frontend/Dockerfile.dev
  #   volumes:
  #     - ./apps/web:/app/apps/web # Montaje para hot-reload
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev

networks:
  moneydiary-network:
    name: moneydiary-dev-network

volumes:
  pgadmin_data:
    name: moneydiary-dev-pgadmin-data
