services:
  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    container_name: moneydiary_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s

  api:
    build:
      context: ../../
      dockerfile: ${API_DOCKERFILE}
      args:
        - APP_VERSION=${APP_VERSION}
    ports:
      - "${API_PORT}:8000"
    environment:
      # Basic configuration
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - APP_VERSION=${APP_VERSION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - ALLOWED_HOSTS_RAW=${ALLOWED_HOSTS_RAW}
      - API_PORT=${API_PORT}

      # OAuth2 Google settings
      - google_client_id=${GOOGLE_CLIENT_ID}
      - google_client_secret=${GOOGLE_CLIENT_SECRET}
      - google_redirect_uri=${GOOGLE_REDIRECT_URI}
      - google_auth_scopes=${GOOGLE_AUTH_SCOPES}

      # JWT settings
      - jwt_secret_key=${JWT_SECRET_KEY}
      - jwt_algorithm=${JWT_ALGORITHM}
      - jwt_access_token_expire_minutes=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - jwt_refresh_token_expire_days=${JWT_REFRESH_TOKEN_EXPIRE_DAYS}

      # Frontend redirect settings
      - frontend_url=${FRONTEND_URL}
      - frontend_auth_callback_path=${FRONTEND_AUTH_CALLBACK_PATH}
      - frontend_auth_error_path=${FRONTEND_AUTH_ERROR_PATH}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - moneydiary-network

  web:
    build:
      context: ../../
      dockerfile: ${WEB_DOCKERFILE}
      args:
        - APP_VERSION=${APP_VERSION}
        - API_URL=${API_URL}
    ports:
      - "${WEB_PORT}:80"
    depends_on:
      - api
    networks:
      - moneydiary-network

networks:
  moneydiary-network:
    name: ${NETWORK_NAME}

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME}
