services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db
    container_name: moneydiary-dev-db
    networks:
      - moneydiary-network

  api:
    extends:
      file: docker-compose.base.yml
      service: api
    container_name: moneydiary-dev-api
    build:
      dockerfile: docker/backend/Dockerfile.dev
    volumes:
      - ../../apps/api:/app/apps/api # Montaje para hot-reload
    environment:
      - DEBUG=true
      - DB_HOST=db
      - DB_USER=moneydiary_user
      - DB_NAME=moneydiary
      - SQLALCHEMY_ECHO=true
      # OAuth2 Google settings
      - google_client_id=${GOOGLE_CLIENT_ID}
      - google_client_secret=${GOOGLE_CLIENT_SECRET}
      - google_redirect_uri=${GOOGLE_REDIRECT_URI}
      - google_auth_scopes=${GOOGLE_AUTH_SCOPE}
      # JWT settings
      - jwt_secret_key=${JWT_SECRET_KEY}
      - jwt_algorithm=${JWT_ALGORITHM}
      - jwt_access_token_expire_minutes=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}
      - jwt_refresh_token_expire_days=${JWT_REFRESH_TOKEN_EXPIRE_DAY}
      # Frontend redirect settings
      - frontend_url=${FRONTEND_URL}
      - frontend_auth_callback_path=${FRONTEND_AUTH_CALLBACK_PATH}
      - frontend_auth_error_path=${FRONTEND_AUTH_ERROR_PATH}
    command: uvicorn apps.api.app.main:app --host 0.0.0.0 --reload --log-level debug
    networks:
      - moneydiary-network

  web:
    extends:
      file: docker-compose.base.yml
      service: web
    container_name: moneydiary-dev-web
    build:
      dockerfile: docker/frontend/Dockerfile.dev
    volumes:
      - ../../apps/web:/app/apps/web # Montaje para hot-reload
    environment:
      - NODE_ENV=development
      # Variables para el frontend que necesita comunicarse con OAuth
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_AUTH_GOOGLE_ENABLED=true
      - VITE_AUTH_CALLBACK_PATH=${FRONTEND_AUTH_CALLBACK_PATH:-/auth/callback}
      - VITE_AUTH_ERROR_PATH=${FRONTEND_AUTH_ERROR_PATH:-/auth/error}
    # Corregido para usar pnpm como en el Dockerfile
    command: pnpm run dev --host
    networks:
      - moneydiary-network

networks:
  moneydiary-network:
    name: moneydiary-network

volumes:
  postgres_data:
    name: moneydiary-dev-postgres-data
  pgadmin_data:
    name: moneydiary-dev-pgadmin-data
