services:
  db:
    build:
      context: ../db
      dockerfile: Dockerfile
    container_name: moneydiary_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: moneydiary_user
      POSTGRES_PASSWORD: moneydiary_password
      POSTGRES_DB: moneydiary
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moneydiary_user -d moneydiary"]
      interval: 10s
      timeout: 5s

  api:
    build:
      context: ../../
      dockerfile: ${API_DOCKERFILE:-docker/backend/Dockerfile}
      args:
        - APP_VERSION=${APP_VERSION:-0.1.0}
    ports:
      - "${API_PORT:-8000}:8000"
    environment:
      # Configuraciones existentes
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-false}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-moneydiary}
      - DB_USER=${POSTGRES_USER:-moneydiary}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-moneydiary_password}
      - SECRET_KEY=${SECRET_KEY:-default-insecure-key}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000}

      # Configuraciones OAuth2 Google
      - google_client_id=${GOOGLE_CLIENT_ID:-}
      - google_client_secret=${GOOGLE_CLIENT_SECRET:-}
      - google_redirect_uri=${GOOGLE_REDIRECT_URI:-http://localhost:8000/api/v1/auth/google/callback}
      - google_auth_scopes=${GOOGLE_AUTH_SCOPES:-openid email profile}

      # Configuraciones JWT
      - jwt_secret_key=${JWT_SECRET_KEY:-}
      - jwt_algorithm=${JWT_ALGORITHM:-HS256}
      - jwt_access_token_expire_minutes=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - jwt_refresh_token_expire_days=${JWT_REFRESH_TOKEN_EXPIRE_DAYS:-7}

      # Configuraciones para la redirección al frontend
      - frontend_url=${FRONTEND_URL:-http://localhost:3000}
      - frontend_auth_callback_path=${FRONTEND_AUTH_CALLBACK_PATH:-/auth/callback}
      - frontend_auth_error_path=${FRONTEND_AUTH_ERROR_PATH:-/auth/error}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - moneydiary-network

  web:
    build:
      context: ../../
      dockerfile: ${WEB_DOCKERFILE:-docker/frontend/Dockerfile}
      args:
        - APP_VERSION=${APP_VERSION:-0.1.0}
        - API_URL=${API_URL:-http://localhost:8000}
    ports:
      - "${WEB_PORT:-3000}:80"
    depends_on:
      - api
    networks:
      - moneydiary-network

networks:
  moneydiary-network:
    name: ${NETWORK_NAME:-moneydiary-network}

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME:-moneydiary-postgres-data}
