name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
        
      - name: Setup SSH directory
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "Host digitalocean" >> ~/.ssh/config
          echo "  HostName ${{ secrets.DO_HOST }}" >> ~/.ssh/config
          echo "  User ${{ secrets.DO_USER }}" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: List files in workspace
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of docker directory (if exists):"
          ls -la docker || echo "Docker directory not found"
          echo "Docker subdirectories (if exist):"
          find docker -type d -ls 2>/dev/null || echo "No subdirectories found"
          echo "Docker files:"
          find docker -type f -ls 2>/dev/null || echo "No files found"

      - name: Copy files to server
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          # Usar rutas absolutas para los archivos
          WORKSPACE="${GITHUB_WORKSPACE}"
          echo "Usando directorio de trabajo: ${WORKSPACE}"
          
          # Verificar los archivos antes de copiar
          ls -la "${WORKSPACE}/docker/docker-compose.prod.yml"
          ls -la "${WORKSPACE}/docker/nginx"
          ls -la "${WORKSPACE}/docker/scripts"
          
          # Copiar con rutas absolutas
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${WORKSPACE}/docker/docker-compose.prod.yml" ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:~/docker-compose.prod.yml
          sshpass -e scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${WORKSPACE}/docker/nginx" ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:~/docker/
          sshpass -e scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${WORKSPACE}/docker/scripts" ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:~/docker/
          sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "chmod +x ~/docker/scripts/*.sh"

      - name: Create .env file on server
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          cat << EOF > .env
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PORT=${{ secrets.MYSQL_PORT }}
          MYSQL_DB=${{ secrets.MYSQL_DB }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          BACKEND_URL=${{ secrets.BACKEND_URL }}
          DOMAIN=${{ secrets.DOMAIN }}
          SSL_EMAIL=${{ secrets.SSL_EMAIL }}
          EOF
          sshpass -e scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null .env ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:~/.env

      - name: Deploy to DigitalOcean
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'ENDSSH'
            cd ~
            mkdir -p docker/nginx/{conf.d,certs,www} docker/data
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/juargo/moneydiary-api:latest
            docker pull ghcr.io/juargo/moneydiary-frontend:latest
            
            # Actualizar configuración de Nginx con el dominio correcto
            if [ ! -z "$DOMAIN" ]; then
              sed -i "s/yourdomain.com/$DOMAIN/g" ~/docker/nginx/conf.d/app.conf
            fi
            
            # Iniciar servicios
            docker-compose -f docker-compose.prod.yml down || true
            docker-compose -f docker-compose.prod.yml up -d
            
            # Configurar certificados SSL si no existen
            if [ ! -f ~/docker/nginx/certs/cert.pem ] && [ ! -z "$DOMAIN" ] && [ ! -z "$SSL_EMAIL" ]; then
              echo "Configurando certificados SSL..."
              ~/docker/scripts/setup-ssl.sh $DOMAIN $SSL_EMAIL production
            fi
          ENDSSH
