name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: moneydiary
          
      # Cuando se crea un release, construir imágenes Docker
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        
      - name: Set up Docker Buildx
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Frontend
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/frontend/Dockerfile
          push: true
          tags: moneydiary/frontend:${{ steps.release.outputs.tag_name }},moneydiary/frontend:latest
          build-args: |
            APP_VERSION=${{ steps.release.outputs.tag_name }}
            
      - name: Build and push Backend
        if: ${{ steps.release.outputs.release_created }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/backend/Dockerfile
          push: true
          tags: moneydiary/backend:${{ steps.release.outputs.tag_name }},moneydiary/backend:latest
          build-args: |
            APP_VERSION=${{ steps.release.outputs.tag_name }}
